name: Signalement de bug
description: Signalez un bug pour nous aider à le corriger
title: "[Bug]: "
labels: ["bug"]
projects: []
assignees:
  - aripot007
body:
  - type: textarea
    id: desc
    attributes:
      label: Description du bug
      description: Décrivez le bug, et le comportement attendu
      placeholder: Dites-nous ce que vous voyez et ce que vous vous attendiez à voir !
      value: |
        "## Description du problème"
        ""
        "Description claire et concise du bug"
        ""
        "## Comportement attendu"
        ""
        "Description du comportement attendu"
        ""
        "## Screenshots"
        ""
        "Si possible expliquez les captures d'écran"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Étapes de reproduction
      description: "Décrivez les étapes à suivre pour reproduire le bug"
      value: |
        1.
        2.
        3.
        ...
  - type: dropdown
    id: browsers
    attributes:
      label: Sur quels navigateurs avez-vous observé le bug ?
      multiple: true
      options:
        - Bornes du bar
        - Firefox
        - Firefox (Mobile)
        - Chrome
        - Chrome (Mobile)
        - Safari
        - Safari (Mobile)
        - Autre
  - type: textarea
    id: additional-info
    attributes:
      label: Informations complémentaires
      description: "Donnez ici les autres informations qui pourraient nous aider"
      placeholder: |
        " - OS: iOS"
